### ISSUE TITLE
Escape brackets

### ISSUE THREAD

**Issue by ftomassetti** [sourrust/karver#8]
In my template I am using the character '{' and it seems to cause the rest of the template to be ignored. Removing it everything is fine.

**Comment by ftomassetti** [comment]
Example:
```
<html>
<head>
    <link rel="stylesheet" type="text/css" href="assets/style.css">
</head>
<body>
<div class="header">
    <h1>Erd Web Server</h1>
</div>
<div class="main">
    <link rel="stylesheet" href="assets/codemirror.css">
    <script src="assets/codemirror.js"></script>
    <script>
      var editor = CodeMirror.fromTextArea(myTextarea, { 
        lineNumbers: true
      });
    </script>
</div>
</body>
</html>
```

The bracket after "myTextarea" is causing the problem.

**Comment by sourrust** [comment]
Alright, I fixed the issue and it now in master. I'm not going to push this to cabal just yet just incase you have other issues to brackets. Reopen this if you do catch anything else, otherwise thank for reporting this bug.

**Comment by ftomassetti** [comment]
I appreciate very much that you fixed so promptly, thank you!
